[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Social Justice: The Role of Intelligent Technologies in Promoting Fairness and Equality"
